### ISSUE TITLE
upgrade to 0.7.2 -  No view rendering, null ModelAndView returned. 

### ISSUE THREAD

**Issue by stella6767** [tschuehly/spring-view-component#16]
I upgraded the library and migrated the code based on the changed usage, but I ended up with a log like the one in the title. What is the problem?

![image](https://github.com/tschuehly/spring-view-component/assets/65489223/bf6d5e61-320f-42a0-be61-65ae628a38a5)

![image](https://github.com/tschuehly/spring-view-component/assets/65489223/3654a45d-5b02-42b7-b809-e5a0285714f0)

![image](https://github.com/tschuehly/spring-view-component/assets/65489223/4aabc447-82a5-4a42-aa72-14891356ef56)

# change to annotationProcessor

![image](https://github.com/tschuehly/spring-view-component/assets/65489223/eb32a0bc-9a54-4e18-987b-cc53f86c9ce6)

![image](https://github.com/tschuehly/spring-view-component/assets/65489223/37ccf17d-98c4-484f-9cb7-1783547665c0)

<img width="1101" alt="image" src="https://github.com/tschuehly/spring-view-component/assets/65489223/3a9233e9-1aaf-4539-b0e4-42c8de026cf5">

just empty

**Comment by tschuehly** [comment]
If you are using Kotlin you need to continue using the kapt dependency notation.

**Comment by tschuehly** [comment]
Could you push this project into a GitHub Repo taht I could check it out?

**Comment by stella6767** [comment]
> Could you push this project into a GitHub Repo that I could check it out?

of course. take me time

**Comment by stella6767** [comment]
> Could you push this project into a GitHub Repo that I could check it out?

I sent an invitation to the repository.

**Comment by tschuehly** [comment]
> > Could you push this project into a GitHub Repo that I could check it out?
> 
> I sent you an invitation to my repository. check dev branch

Can you try using .kte instead of .jte? Then the correct compiler should be used

**Comment by stella6767** [comment]
> > > > Could you push this project into a GitHub Repo that I could check it out?
> > > 
> > > 
> > > I sent you an invitation to my repository. check dev branch
> > 
> > 
> > Can you try using .kte instead of .jte? Then the correct compiler should be used
> 
> wait a minute. sir

cant apply kapt dependency notation... i will try it tomorrow

**Comment by stella6767** [comment]
> > > > > Could you push this project into a GitHub Repo that I could check it out?
> > > > 
> > > > 
> > > > I sent you an invitation to my repository. check dev branch
> > > 
> > > 
> > > Can you try using .kte instead of .jte? Then the correct compiler should be used
> > 
> > 
> > wait a minute. sir
> 
> cant apply kapt dependency notation... i will try it tomorrow

![image](https://github.com/tschuehly/spring-view-component/assets/65489223/c4fdd40b-7c29-4389-8ee6-addf6a4c364a)

cant find solution.
i tried your kte example but i got this error.
can you explain that why it is happening?

**Comment by tschuehly** [comment]
I think it's an issue with the local development compilation for kotlin, I can reproduce the issue!
when setting `spring.view-component.local-development: false` then it works again. Do this as a workaround!
I will try to find a solution and release a fix!
