### ISSUE TITLE
spring-view-component-core absent on https://repo1.maven.org/maven2/de/tschuehly/

### ISSUE THREAD

**Issue by linux-china** [tschuehly/spring-view-component#3]
spring-view-component-core is required for spring-view-component-thymeleaf, and it could not found on Maven Central Repository.  Thanks.

```xml
<dependency>
  <groupId>de.tschuehly</groupId>
  <artifactId>spring-view-component-core</artifactId>
  <version>0.5.1</version>
   <scope>compile</scope>
</dependency>
```

**Comment by tschuehly** [comment]
Hello @linux-china,

yes I'm currently still trying to get everything up on Maven. I will write again if it works!

**Comment by tschuehly** [comment]
Hello @linux-china this issue is fixed, just reopen the issue if you still have problems!
