### ISSUE TITLE
do you have a plan that support .kte file

### ISSUE THREAD

**Issue by stella6767** [tschuehly/spring-view-component#9]
i currently using spring-view-component-jte.
i change little bit code. 

![image](https://github.com/tschuehly/spring-view-component/assets/65489223/5c9942a5-380c-4e6e-9c24-fe41cdce4ba4)

![image](https://github.com/tschuehly/spring-view-component/assets/65489223/75718651-8a08-4750-8f94-af30cdc59389)

if you dont mind, did you have a plan for support multiple suffix about .jte and .kte,

**Comment by tschuehly** [comment]
.kte can now be configured in 0.7.2-SNAPSHOT
